t1 = (2,4,3,6,7,4,8,9,5,6,7)
t2 = ("apple","banana","oranges","choclate","mango","grape","fossil_light")

print("touple t1",t1)
print("length of t1:" , len(t1))
print("count of 7 in t1:" , t1.count(7))
print("index of 3 in t1" , t1.index(3))
print("concatenation t1 + t2:",t1 + t2)
print("t1 repeated twice:",t1 * 2)
print("is banana is t2:" , "banana" in t2)
print("minimum in t1" , min(t1))
print("maximum in t1:" , max(t1))
print("sum of t1" , sum(t1))
print("slice t1[1:4]" , t1[1:4])
print("reversed t1:" , t1[::-1])
print("sorted t1: " , sorted(t1))
print("unique elements in t1:" , tuple(set(t1)))
print("all elements > 5 in t1:" , all( x>10 for x in t1))
print("any element == 7 in t1" , any(x == 7 for x in t1))
